name: Bump Dolt on Chocolatey

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
      force:
        description: 'force push package'
        required: false
        default: 'false'
  repository_dispatch:
    types: [ bump-choco ]

jobs:
  winget-bump-wd:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Bump Dolt Chocolately
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
      - name: Install AU
        run: cinst au
      - name: Build Package
        working-directory: ./dolt
        run: |
          ./update.ps1
        env:
          au_Push: 'false'
          VERSION: ${{ github.event.inputs.version }}
      - name: Test Package Installer
        working-directory: ./dolt
        run: Test-Package $Install
      - name: Dolt Version
        run: |
          refreshenv
          $env:Path += ';C:\Program Files\Dolt\bin\'
          dolt version
      - uses: EndBug/add-and-commit@v7
        with:
          message: "[ga-bump-dolt-chocolatey] Bumping Dolt on Chocolatey ${{ github.event.inputs.version }}"
          add: "."
          cwd: "."
      - name: Push Package to Chocolatey
        run: Push-Package
        working-directory: ./dolt
        env:
          api_key: ${{ secrets.CHOCO_API_KEY }}
          au_Force: ${{ github.event.inputs.force }}
  winget-bump-rd:
    if: ${{ github.event_name == 'repository_dispatch' }}
    name: Bump Dolt Chocolately
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
      - name: Install AU
        run: cinst au
      - name: Build Package
        working-directory: ./dolt
        run: |
          ./update.ps1
        env:
          au_Push: 'false'
          VERSION: ${{ github.event.client_payload.version }}
      - name: Test Package Installer
        working-directory: ./dolt
        run: Test-Package $Install
      - name: Dolt Version
        run: |
          refreshenv
          $env:Path += ';C:\Program Files\Dolt\bin\'
          dolt version
      - uses: EndBug/add-and-commit@v7
        with:
          message: "[ga-bump-dolt-chocolatey] Bumping Dolt on Chocolatey ${{ github.event.client_payload.version }}"
          add: "."
          cwd: "."
      - name: Push Package to Chocolatey
        run: Push-Package
        working-directory: ./dolt
        env:
          api_key: ${{ secrets.CHOCO_API_KEY }}
