# name: Bump Dolt on Chocolatey

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'SemVer format release tag, i.e. 0.24.5'
        required: true
  repository_dispatch:
    types: [ bump-choco ]

jobs:
  winget-bump:
    name: Bump Dolt Chocolately
    runs-on: windows-2019
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
      - name: Install AU
        run: cinst au
      - name: Install choco
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          choco outdated
      - name: Build Package
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: ./dolt
        run: |
          ./update.ps1
        env:
          au_Push: 'false'
          api_key: ${{ secrets.CHOCO_API_KEY }}
          github_api_key: ${{ secrets.REPO_ACCESS_TOKEN }}
          github_user_repo: "dolthub/dolt"
          VERSION: ${{ github.event.inputs.version }}
      - name: Test Package Installer
        if: ${{ github.event_name == 'workflow_dispatch' }}
        working-directory: ./dolt
        run: |
          ls -a
          ls ../chocolatey/dolt
          choco install dolt -s .
      # - name: Test Package Uninstaller
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   working-directory: ./dolt
      #   run: |
      #     Test-Package -Uninstall

      # - name: Changes detected
      #   id: detect-changes
      #   run: |
      #     changes=$(git status --porcelain)
      #     if [ ! -z "$changes" ]; then
      #        echo "::set-output name=has-changes::true"
      #     fi

      # - uses: EndBug/add-and-commit@v7
      #   # if: ${{ steps.detect-changes.outputs.has-changes == 'true' }}
      #   with:
      #     message: "[ga-bump-dolt-chocolatey] Bumping Dolt on Chocolatey ${{ github.event.inputs.version }}"
      #     add: "."
      #     cwd: "."

      # - name: Create Winget PR
      #   if: ${{ github.event_name == 'repository_dispatch' }}
      #   run: |
      #     iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
      #     .\wingetcreate.exe update DoltHub.Dolt -u $Env:URL -v $Env:VERSION -t $Env:TOKEN --submit
      #   env:
      #     TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
      #     VERSION: ${{ github.event.client_payload.version }}
      #     URL: ${{ format('https://github.com/dolthub/dolt/releases/download/{0}/dolt-windows-amd64.msi', github.event.client_payload.version) }}
